<style type="text/css">
.portlet-title h4{ color:#3c3a3a; text-align:center; font-weight:bold;}
</style>
<!-- Add / Edit Style Page -->
<div class="portlet box grey">
	<div class="portlet-title">
    	<h4><i class="icon-copy"></i>Edit User Information</h4>
    </div>
    <div class="portlet-body form">
		<?php echo $this->getHelper('Messages')->getMessages();?> 
        <?php echo $this->form ;?>
    </div>
</div>

