<style type="text/css">
.SubCatNamePage{color: #545454 !important;text-decoration: none !important;font-size: 15px;}
.header .close { position: absolute; right: -7px;background-color: white; padding: 2px 6px;border-radius: 50%; opacity: 1; top: -2%;border:2px solid #0bb8e3;color:#0bb8e3;z-index: 1;}
.job_post_outter_div .form-group>:first-child { text-align:left;font-weight: 700;font-family: 'PT Sans', sans-serif;display: inline-block;color:black;margin-bottom: 5px;padding:0px;font-size:17px;}	

</style>

<?php
$categoriestop = $this->categoriestop;
$categorieslist = $this->categorieslist;
$totalcat= count($categorieslist);
//prn($categoriestop);
$MoveToservice = $this->MoveToservice;
$modelSuper=new Application_Model_SuperModel();  

$cat_searchlist = $this->cat_searchlist;
$jsonServices = json_encode($this->cat_searchlist);
//prd($jsonServices);
$showjobPostModel = $this->showjobPostModel;

?>
<section>
	<div class="containerfluid home_improve_bg">
    	<h3><?=$MoveToservice['service_name']?></h3>
        <p>Complete your project with the right professionals</p>
        		<div class="search_form_outter_div">
       		 <form method="get" action="#" class="profile_form">
                            <div class="row search_form">
                                    <div class="rewilla_home_service_div">
                                        <input  type="text" name="services" placeholder="What service do you need?" id="searchServices" class="form-control what_need service_serach_box" />
                                        
                                        <img class="search_img " src="<?php echo HTTP_SITEIMG_PATH?>/search_icon.png"  />
                                    </div>
                                    
                                    <div class="rewilla_home_service_button_div">
                                         <button type="submit" class="btn-custom get_start">Get Started</button>
                                    </div>
                            </div>
                        </form>
        </div>
            
        
    </div>
    <div class="allservice" >
        <div class="container padding_bottom_40">
            <div class="col-sm-12 padding_10">
            	<div class="popular_home_div">
                	<h3>Popular <?=$MoveToservice['service_name']?> Services</h3>
                </div>
                <div class="row effects text-center">
                <?  foreach($categoriestop as  $key => $categories1) { //prn($categories1);?>
				<? 
					 $if_has_sub_cat = $modelSuper->Super_Get("services","service_parent_id='".$categories1['service_parent_id']."' && service_sub_parent_id='".$categories1['service_id']."'","fetchAll");
				?>
                    <div class="casa_9_img" style="background-image:url(<?php echo HTTP_SERVICE_IMAGES_PATH.'/'.$categories1['service_image'];?>);"> 
                        <div class="overlay_service_name">
                        	<? if(count($if_has_sub_cat)>0){?>
                            <a  href=" <?php  echo $this->url(array('service_id'=>$categories1['service_id'],"service_name"=>$categories1['service_name'],'service_parent_id'=>$categories1['service_parent_id']),'front_seeallsubcategory')?>" class="expand"> <?php echo $categories1['service_name'] ?></a>
                            <? } else{?>
                             <a class="expand"> <?php echo $categories1['service_name'] ?></a>
                            <? } ?>
                        </div>       
                    </div>
                 <? } ?>
                </div>
                 <? if($totalcat>0){?> 
             		   <div class="popular_home_div">
                	<h3>More <?=$MoveToservice['service_name']?> Services</h3>
                </div>
                <? } ?> 
                
                
                
                <div class="main_container">
               		    <? foreach($categorieslist as  $categories2) {  ?>
                        	<div class="pin">
                            	<div class="holder">
                                        <a class="category_heading" href="<?php  echo $this->url(array('service_id'=>$categories2['service_id'],"service_name"=>$categories2['service_name'],'service_parent_id'=>$categories2['service_parent_id']),'front_seeallsubcategory')?>"><?php echo $categories2['service_name']?></a>
                                        
                                        <?	$extra= array('order'=>'service_name asc');
										 $subCat = $modelSuper->Super_Get("services","service_parent_id='".$categories2['service_parent_id']."' && service_sub_parent_id='".$categories2['service_id']."'","fetchAll",$extra); ?>
                                         
                                        <ul>
                                            <?  foreach($subCat as  $subcat) {  ?>
                                            	
                                                <li> 
                                              <!--  <a onclick="requestjobModel(<?php //echo $subcat["service_id"]?>)" href="#" class="" data-toggle="modal" data-target="#<?//=$subcat['service_id']?>" ><p> <?php //echo $subcat['service_name'] ?></p></a></li>-->
                                          
													 <a class="SubCatNamePage Cursor" onclick="postjobfromCatName(<?=$categories2['service_id']?>)"> <?php echo $subcat['service_name'];?></a>      
                                                </li>
                                            <? } ?>
                                        </ul>
                                 </div>    
                             </div>  
                        <? }?>
                        
               </div>
               
            </div>
        </div>
    </div>
</section> 


 <div class="modal fade" id="addprojectmodel2" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        <!--  <h4 class="modal-title">Modal Header</h4>-->
        </div>
        <div class="modal-body" style="padding:0px;">
         
        </div>
       <!-- <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>-->
      </div>
      
    </div>
  </div>

<div class="modal fade" id="addprojectmodel" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="header">
          <button type="button" class="close" data-dismiss="modal" onclick="closeJobModal(1)">&times;</button>
        </div>
        <div class="modal-body" style="padding:0px;">
        </div>
      </div>
    </div>
  </div>






<script type="text/javascript">

	var JsonServices = JSON.parse('<?=$jsonServices?>');//alert(JsonServices)
$(document).ready(function(e) {

    $('.main_container').masonry
 ({
        // options
        itemSelector : '.pin',
        isAnimated: true,
        isFitWidth: true
    });
 
});

 $(function(){
           var choices = Array() ;
			for(var i=0;i<JsonServices.length;i++){
				choices.push(JsonServices[i].service_name);
			}
            $('#searchServices').autoComplete({
                minChars: 1,
                source: function(term, suggest){
                    term = term.toLowerCase();
                    var suggestions = [];
                    for (i=0;i<choices.length;i++)
                        if (~choices[i].toLowerCase().indexOf(term)) suggestions.push(choices[i]);
                    suggest(suggestions);
                }
            });
	 });



</script>

<script type="text/javascript">
var new_post_job_id = '<?=$showjobPostModel?>';

<? if($showjobPostModel!='' && $showjobPostModel!='\+d'){ ?>
$(document).ready(function(e) {
	 afterLoginPostJobConditionChk(<?=$showjobPostModel?>)
});
<? } ?>
</script> 



<script type="text/javascript">
var Logged_user='0';
<?
if(isset($this->user->user_id) && $this->user->user_id!="")
{
?>
Logged_user=parseInt('<?=$this->user->user_id?>');

<? }?>

if(Logged_user>0)
{
	var file_cnt=-1;
	var file_id;
	var FILE_PATH="<?=SITE_HTTP_URL."/public/resources/uploads/image_"?>"+Logged_user+"/";
	var THUMB_FILE_PATH="<?=SITE_HTTP_URL."/public/resources/uploads/image_"?>"+Logged_user+"/thumbnail/";
	var MEDIUM_FILE_PATH="<?=SITE_HTTP_URL."/public/resources/uploads/image_"?>"+Logged_user+"/medium/";
}
</script>      

<script id="template-upload" type="text/x-tmpl">

{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-upload fade">
      	<td>
            
        </td>
	    <td>
            <span class="preview"></span>
        </td>
        <td  class="hidden-xs">
            <p class="name">{%=file.name%}</p>
            <strong class="error text-danger"></strong>
        </td>
        <td  class="hidden-xs">
            <p class="size">Processing...</p>
            <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div class="progress-bar progress-bar-success" style="width:0%;"></div></div>
        </td>
        <td>
            {% if (!i && !o.options.autoUpload) { %}
                <button class="btn btn-primary start" disabled>
                    <i class="glyphicon glyphicon-upload"></i>
                    <span>Start</span>
                </button>
            {% } %}
            {% if (!i) { %}
                <button class="btn btn-warning cancel">
                    <i class="glyphicon glyphicon-ban-circle"></i>
                    <span>Cancel</span>
                </button>
            {% } %}
        </td>
    </tr>
{% } %}
</script>

<script id="template-download" type="text/x-tmpl">

   
{% for (var i=0, file; file=o.files[i]; i++) { 
file_cnt++;
file_id="files_"+file_cnt;

$(".banner_img_instruction").css('display','block');

	if (file.error)
	{
		if(file.error=="Image requires a minimum width")
		{
			alert('Image should be of atleast 200 x 100 pixel.');
		}
		else
		{
	 		alert(file.error);
		}
	}
	else
	{
		
%}
    <tr class="template-download fade">
        <td>
			<div class="radio">
            <span class="preview" style="cursor:pointer;">
                <input type="radio" name="select_banner[]" value="{%=file.name%}" style="margin-left:0px;"/>
            </span>
			</div>
        </td>
		<td>
            <span class="preview" style="cursor:pointer;">
                {% if (file.thumbnailUrl) { %}
                    <img draggable="false"  src="{%=file.thumbnailUrl%}">
                {% } %}
            </span>
        </td>
        <td class="hidden-xs">
            <p class="name">
                {% if (file.url) { %}
                    <a  title="{%=file.name%}" download="{%=file.name%}" {%=file.thumbnailUrl?'data-gallery':''%}>{%=file.name%}</a>
                {% } else { %}
                    <span>{%=file.name%}</span>
                {% } %}
            </p>
            {% if (file.error) { %}
                <div><span class="label label-danger">Error</span> {%=file.error%}</div>
            {% } %}
        </td>
        <td  class="hidden-xs">
            <span class="size">{%=o.formatFileSize(file.size)%}</span>
        </td>
        <td>
            {% if (file.deleteUrl) { %}
                <button  class="btn btn-danger delete" data-type="{%=file.deleteType%}" data-url="{%=file.deleteUrl%}"{% if (file.deleteWithCredentials) { %} data-xhr-fields='{"withCredentials":true}'{% } %}>
                    <i class="glyphicon glyphicon-trash"></i>
                    <span>Delete</span>
                </button>
            {% } else { %}
                <button class="btn btn-warning cancel">
                    <i class="glyphicon glyphicon-ban-circle"></i>
                    <span>Cancel</span>
                </button>
            {% } %}
        </td>
    </tr>
{% 
		}
} 
		$('img').on('mousedown', function(e) {
		e.preventDefault();
		});
		
		$('img').bind("contextmenu", function(e) {
		e.preventDefault();
		});
%}


</script>




