<?php
?>
<style type="text/css">
.modelAllowHeader{background-color: #0bb8e3;color: white;}
.highlightJobCss{ background-color:#b8ecf9 !important;}
</style>
<div class="row">
 	<div class="col-md-12 ">
		<!-- BEGIN SAMPLE FORM PORTLET-->
		<div class="portlet box purple">
			<div class="portlet-title">
				<div class="caption"><i class="<?php echo $this->pageIcon?>"></i> <?php echo $this->pageHeading?> </div>
			</div>
			
			<div class="portlet-body">
			
			
				<div class="table-toolbar">
                
 					<div class="btn-group">
                    </div>	
				</div>
 			
 					<table class="table table-striped table-bordered table-hover dataTable" id="sample_1">
						<thead>
							<tr>
                                <th width="5%">S.NO</th>
                                <th>Posted By</th>
                                <th>Title</th>
 								<th>Job Status</th>
                                 <th>Added On</th>
                                <th>More Quote Status</th>
                                <th  width="10%">View</th>
							</tr>
						</thead>
						<tbody>
						</tbody>
					</table>
			</div>
		</div>
		<!-- END SAMPLE FORM PORTLET-->
	</div>


</div>

<!--Send Reminder to admin-->
<div id="sendReminderSP" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
    	
                <div class="modal-header modelAllowHeader">
                    <h4 class="modal-title model_title_pay">Allow More Quote</h4>
                </div>
                <div class="modal-body model_body_pay ">
                   
                </div>
    </div>
  </div>
</div>

<?
$NotiId = '';
if(isset($_GET['noticeId']) && !empty($_GET['noticeId'])){
		$NotiId = $_GET['noticeId'];
	}
?>


<script type="">
$(".toggle").click(function(e) {
});
</script>

<!-- END EXAMPLE TABLE PORTLET-->
<script type="text/javascript" charset="utf-8">
var NotiId = '<?=$NotiId;?>';
$(document)	 .ready(function(e) {
	$('#sample_1').dataTable( {
		"bProcessing": true,
		"bServerSide": true,
 		"sAjaxSource": "<?php echo $this->baseUrl()?>/privatepanel/job/getjobs" ,
		"aaSorting": [],
		"aoColumnDefs": 
		 [
			{ "bSortable": false, "aTargets": [0,4,5] },
 		 	/*{ "sClass": "hidden-767", "aTargets": [ 1 ] },
			{ "sClass": "hidden-480", "aTargets": [ 5 ] },
			{ "sClass": "hidden-320", "aTargets": [6] }*/
		 ],
		"iDisplayLength":50,
	    "aLengthMenu": [[50, 100, 500, -1], [50, 100, 500, "All"]],
		"fnDrawCallback": function( oSettings ) {
			re_init();
		}
	} );
	
	if(NotiId!=''){
		
		
		window.setTimeout(function(e){
			$("#AccDeclineDiv_"+NotiId).closest("td").addClass('highlightJobCss');
			 $('html, body').animate({
			   scrollTop: $("#AccDeclineDiv_"+NotiId).offset().top
			   
			 }, 1000); 
			},500);
		}
	
});
</script>

