<div class="row choose_form">
  <div  class="col-md-12 welcome_txt"> WELCOME TO YOLOCAL </div>
  <div  class="col-md-12 img_div"> <img src="<?=HTTP_SITEIMG_PATH?>/lap.jpg" class="img-responsive" /> </div>
  <div  class="col-md-offset-1 col-md-10">
    <div class="content_div">
      <div class="row">
        <div class="col-md-6 want_to_hire">
          <div class="">
            <p class="hire_div">Hire Skilled People, best of them.</p>
            <p class="hire_des">Vivamus congue rhoncus sem et placerat. Fusce nec nunc lobortis lorem ultrices facilisis. Ut dapibus blandit nunc, et consectetur dui.</p>
            <p class="text-right button_div"><a  class="want_to_hire_button" href="<?php echo $this->url(array('user_type'=>'client'),'front_register_client')?>" >Want To Hire ?</a></p>
          </div>
        </div>
        <div class="col-md-6">
          <div class="want_to_be_hire">
            <p class="hire_div">Easiest way to find your dream job.</p>
            <p class="hire_des">Vivamus congue rhoncus sem et placerat. Fusce nec nunc lobortis lorem ultrices facilisis. Ut dapibus blandit nunc, et consectetur dui.</p>
            <p class="text-right button_div"><a  class="want_to_hire_button" href="<?php echo $this->url(array('user_type'=>'guard'),'front_register_client')?>" >Want to be Hired ?</a></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
