
<div class="signup_pagesbg">
	<div class="row">
    	<div class="col-md-6 col-md-offset-3 margin_class_login_for">
        	<div class="signup_pagesbg_inner">
            	<h1 class="signup_head text-center">
					<a href="<?=$this->baseUrl('/index')?>"><img src="<?=HTTP_SITE_IMAGES?>/admin_logo.png"  alt="Logo"/></a>
                </h1>
				<div class="content_pad_div">
                	<div class="text-center label_left"><?=$this->form?></div>
             
                  <br />
                           <div class="fullwidthdiv text-center forgot_password"><a href="<?php echo $this->url(array(),'front_login')?>">Sign In</a></div>

                </div>
            </div>
        </div>
    </div>
</div>

