<div class="signup_pagesbg">
	<div class="row">
    	<div class="col-md-6 col-md-offset-3">
        	<div class="signup_pagesbg_inner">
            	<h1 class="signup_head text-center">
					<a  href="<?=$this->baseUrl('/index')?>"><img src="<?=HTTP_SITE_IMAGES?>/admin_logo.png"  alt="Logo"/></a>
                </h1>
                <h1 class="signup_head text-center">
                    CLIENT SIGNUP
                </h1>
				<div class="content_pad_div">
                	<div class="text-center label_left"><?=$this->form?></div>
                  <br />
                <div class="text-center">You will receive a activation email on your registered email to activate your account </div>
                  <br />
                 <div class="text-center"><a href="<?=$this->baseUrl()?>/login">Already have an account</a> | <a href="<?=$this->baseUrl()?>/forgot-password">Forgot Password</a></div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
$(document).ready(function(e) {
    $('#cancel').click(function(e) {
     
	   window.location.href=baseUrl+'/index';
    });
});
</script>
