
<div class="login"> 
 
  <!-- BEGIN LOGIN -->
  <div class="content">
  	<div class="fullwidthdiv text-center login_title">Forgot Password?</div>
    <div class="content_padding">
      <?=$this->form?>
      <p>&nbsp;</p>
           <div class="fullwidthdiv text-center forgot_password"><a href="<?php echo $this->url(array(),'front_login')?>">Sign In</a></div>

    </div>

  </div>
  <!-- END LOGIN --> 
  
  
</div>
