
<div class="login"> 
 
  <!-- BEGIN LOGIN -->
  <div class="content">
  	<div class="fullwidthdiv text-center login_title">Login to your account</div>
    <div class="fullwidthdiv text-center">
                    <a  class="ColorText facebook" href="<?=$this->baseUrl('social/fblogin')?>"><span class="fa fa-facebook-f"></span>FACEBOOK</a>
                        &nbsp;&nbsp;     
                   <a  class="ColorText google" href="<?=$this->baseUrl('social/googlelogin/loginyes/1/')?>"><span class="fa fa-google-plus"></span> GOOGLE+</a>
    </div>
    <div class="content_padding">
      <?=$this->form?>
      <p>&nbsp;</p>
           <div class="fullwidthdiv text-center forgot_password"><a href="<?php echo $this->url(array(),'front_forgotpassword')?>"> Forgot your Password?</a></div>

    </div>

  </div>
  <!-- END LOGIN --> 
  
  
</div>
