<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en" >
<!--<![endif]-->
<!-- BEGIN HEAD -->
<head>

<?php 
	echo $this->headMeta();
	echo $this->headTitle('Admin Login');
	echo $this->headLink();
?>

<script> var baseUrl = '<?php echo APPLICATION_URL?>';</script>

</head>
<!-- END HEAD -->


<!-- BEGIN BODY -->
<body class="login">

	
	
	
	<!-- BEGIN SIDEBAR TOGGLER BUTTON -->
	<div class="menu-toggler sidebar-toggler"></div>
	<!-- END SIDEBAR TOGGLER BUTTON -->
	
	
	<!-- BEGIN LOGIN -->
	<div class="content">
		<!-- BEGIN LOGO -->
	<div class="logo">
		<a href="<?=SITE_HTTP_URL."/index"?>">
		<img class="maxWidthLogo"  src="<?php echo HTTP_SITE_IMAGES?>/logo.png" alt=""/>
		</a>
	</div>
    <hr>
	<!-- END LOGO -->
		<?php echo $this->getHelper("Messages")->getMessages();?>
		<!-- BEGIN LOGIN FORM -->
		<form class="login-form"   method="post">
			<div class="form-title text-center">Login to your account</div>
			
			<div class="form-group">
				<!--ie8, ie9 does not support html5 placeholder, so we just show field title for that-->
				<label class="control-label visible-ie8 visible-ie9">Username</label>
				<div class="input-icon">
					<i class="fa fa-user"></i>
					<?php echo $this->form->user_email?>
				</div>
			</div>
			<div class="form-group">
				<label class="control-label visible-ie8 visible-ie9">Password</label>
				<div class="input-icon">
					<i class="fa fa-lock"></i>
						<?php echo $this->form->user_password?>
				   </div>
			</div>
			<div class="form-actions overflow_hidden text-center">
				
				<button type="submit" class="btn blue  login_btn"> Login <i class="m-icon-swapright m-icon-white"></i> </button>
			</div>
		</form>
		<!-- END LOGIN FORM -->
	</div>
	<!-- END LOGIN -->
	
	<!-- BEGIN COPYRIGHT -->
	<div class="copyright">
		 <?=date('Y')?> &copy; 
		<?php echo $this->site_configs['site_title'];?> 
	</div>


	<?php echo $this->headScript(); // Javascript?>


	<script type="application/javascript">
	jQuery(document).ready(function() {     
		Metronic.init(); // init metronic core components
		Login.init();
	});
	</script>
</body>
</html>