<?php 
		
	$params = array();	
	$params=Zend_Controller_Front::getInstance()->getRequest()->getParams();
?>
<?php 

 
$queryString = "";


if(@count($this->getHelper('baseUrl')->view->queryString) > 0 && @is_array($this->getHelper('baseUrl')->view->queryString))
$queryString = http_build_query($this->getHelper('baseUrl')->view->queryString); 

 $page_vars=$this->getVars(); 
  

?>


<div>
	<div class="col-md-12 padding0">        
        <?php if($this->pageCount){?>
         <div class="text-right">
         	<ul class="pagination fontsize14 textupper" style="margin:0 0 3px;">
            	<?
                	if($this->current==$this->first)
					{
						$display_class_pre='hide';
					}
					else
					{
						$display_class_pre='';
					}
				?>
                <?php /*?> <?php if (isset($this->first)){ ?>
                    <li><a href="<?php echo $this->url(array_merge($params,array('page' => $this->first))); ?>">First</a> </li>
                <?php }else{ ?>
                    <li class="disabled"><a href="#">First</a> </li>
                <?php } ?><?php */?>
                <?php if (isset($this->previous)){ ?>
                    <li><a href="<?php echo $this->url(array_merge($params,array('page' => $this->previous))); ?>">«</a> </li>
                <?php }else{ ?>
                    <li class="disabled"><a href="#">«</a> </li>
                <?php } ?>
            	<?php 
                    foreach($this->pagesInRange as $page=>$pageno){
                        if($this->current!=$pageno){ ?>		
                        <li class="fontsize14"> <a href="<?php echo $this->url(array_merge($params,array('page' => $page))); ?>" ><?=$pageno?></a></li>
                        <?php }else{ ?>
                        <li class="disabled fontsize14"><a href="#"><?=$pageno?></a></li>
                        <?php }
                    }
                ?>
                 <?php if(isset($this->next)){?>
                    <li><a href="<?php echo $this->url(array('page' => $this->next)).(($queryString!="")?"?".$queryString:""); ?>">»</a></li>  
                 <?php }else{ ?>
                    <li class="disabled"><a href="#">»</a></li>  
                <?php } ?>
                <?php /*?><?php if(isset($this->last)){?>
                    <li><a href="<?php echo $this->url(array('page' => $this->last)).(($queryString!="")?"?".$queryString:""); ?>">Last</a></li>  
                 <?php }else{ ?>
                    <li class="disabled"><a href="#">Last</a></li>  
                <?php } ?><?php */?>
            </ul>
         </div>
        
        <div class="clearfix"></div>
        <div class="row" style="display:none;">
            <div class="col-md-12 col-xs-12 col-sm-12 text-right">
            	<h5 style="font-weight:normal"><?php echo $this->firstItemNumber; ?> - <?php echo $this->lastItemNumber; ?> of  <?php echo $this->totalItemCount; ?></h5>
            </div>
        </div>

        
        <?php }?>
     </div>
</div>

 
<script type="text/javascript">
function changeItemCount(sel){
	var currUrl='<?php echo $this->url();?>';	
	var currUrl='<?php echo $this->url(array('itemcountpage' => 'setitemcount')) ?>';	
	if(currUrl.indexOf("?")>=0){
		currUrl="<?php $this->url() ?>?itemcountpage="+sel.value ;
	}else{
		var currUrl='<?php echo $this->url(array('itemcountpage' => 'setitemcount')).(($queryString!="")?"?".$queryString:""); ?>';	
		currUrl=currUrl.replace("setitemcount",sel.value);	
	}

	window.location=currUrl ;
}
</script>
