<?php /*?>

<div>
	<? if($this->page_id=='2') { ?>
    <br />
	<h2 class="static-content-heading text-center" ><big><big><?php echo $this->content['page_title'];?></big></big></h2>
    <? } ?>
	

    <?php echo $this->content['page_content']?>

</div>
<?php */?>

<!--HOW IT WORKS-->

<!--how background image-->

<div class="container-fluid">
	<div class="how_bg" style="background-image:url(<?php echo HTTP_SITEIMG_PATH?>/about3.jpg); background-size:cover; height:400px;">
    		<h3>How It Works</h3>
    </div>
</div>

<!--how slider-->

<div class="container">
	<div class="how_slide_div">
            <div class="how_steps_outter">
          		  <div class="how_steps">
                   		 <div class=" slider_how owl-carousel owl-theme">
                                <div class="item">
                                    <div class="inner_div_slider">
                               		 	<h3 class="how_steps_h">Register as service provider or as client</h3>
                                    </div>    
                                </div>
                                
                                <div class="item">
                                	<div class="inner_div_slider">
                               			 <h3 class="how_steps_h">Login to your account</h3>
                                     </div>
                                </div>	
                                
                                <div class="item">
                                	<div class="inner_div_slider">
                              			 <h3 class="how_steps_h">Service provider give details about services</h3>
                                    </div>
                                </div>   
                                
                                <div class="item">
                                	<div class="inner_div_slider">
                               			 <h3 class="how_steps_h">Client can request to service provider for services</h3>
                                    </div>
                                </div> 
                                
                                <div class="item">
                                	<div class="inner_div_slider">
                               			 <h3 class="how_steps_h">Service provider will handle the request</h3>
                                    </div>
                                </div>      
                   		 </div>
                   </div>    
            </div>  
	</div>
</div>   

<div class="container">
     <div class="how_para">
     		<h3>The Story Behind Our Story</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus hendrerit tincidunt risus nec venenatis. Morbi non feugiat purus, nec euismod tellus. Morbi ac euismod sapien, ut finibus odio. Ut mollis neque eget condimentum scelerisque. Sed dignissim arcu sed imperdiet pretium. Maecenas in neque nec ex feugiat dignissim ac ut est. Vivamus risus massa, blandit auctor mollis in, pulvinar eu urna.</p>
            <a href="#">Read More</a>
     </div>
</div>

<div class="containe-fluid">
<div style="background-image:url(<?php echo HTTP_SITEIMG_PATH?>/offset_img.jpg); background-size:cover; height:700px;">
	<div class="offset_outter_div">
		<div class="col-sm-offset-6 col-sm-6 off_right_div">
       			
                <div class="comments_div">
               <i class="fa fa-quote-left" aria-hidden="true"></i>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus hendrerit tincidunt risus nec venenatis. Morbi non feugiat purus, nec euismod tellus. Morbi ac euismod sapien, ut finibus odio. Ut mollis neque eget condimentum scelerisque. Sed dignissim arcu sed imperdiet pretium. </p>
                <i class="fa fa-quote-right" aria-hidden="true"></i>
                 <h4 class="david_c">David Goal</h4>
                </div>
        </div>
        
        <div class=" col-sm-6  off_right_div">
       			<div class="comments_div">
               <i class="fa fa-quote-left" aria-hidden="true"></i>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus hendrerit tincidunt risus nec venenatis. Morbi non feugiat purus, nec euismod tellus. Morbi ac euismod sapien, ut finibus odio. Ut mollis neque eget condimentum scelerisque. Sed dignissim arcu sed imperdiet pretium. </p>
                <i class="fa fa-quote-right" aria-hidden="true"></i>
                 <h4 class="david_c">David Goal</h4>
                </div>
        </div>
   </div>
        
</div>
</div>

<div class="container">
     <div class="how_para">
     		<h3>The Story Behind Our Story</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus hendrerit tincidunt risus nec venenatis. Morbi non feugiat purus, nec euismod tellus. Morbi ac euismod sapien, ut finibus odio. Ut mollis neque eget condimentum scelerisque. Sed dignissim arcu sed imperdiet pretium. Maecenas in neque nec ex feugiat dignissim ac ut est. Vivamus risus massa, blandit auctor mollis in, pulvinar eu urna.</p>
            <a href="#">Read More</a>
     </div>
</div>

<div class="container-fluid">

		<div class="custom_container_how">
        	<div class="col-sm-12">
                <div class="globel_status">
                    <h3>Lorem ipsum dolor</h3>
                    <h5>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus hendrerit tincidunt risus nec venenatis.</h5>
                </div>    
        
                <div class="reviews_clients_div">
                    
                    <div class="col-sm-4 counting_client">
                        <img src="<?php echo HTTP_SITEIMG_PATH?>/icon-globe.png"  alt="" class="img-responsive margin_img_left"/>
                         <h1>15,000 <span> +</span></h1>
                          <h5>customers, 90 countries</h5>
                    </div>
                    
                    <div class="col-sm-4 counting_client">
                        <img src="<?php echo HTTP_SITEIMG_PATH?>/icon-users.png"  alt="" class="img-responsive margin_img_left_2"/>
                         <h1>3,100 <span> +</span></h1>
                          <h5>agency partners</h5>
                    </div>
                    
                    <div class="col-sm-4 counting_client">
                        <img src="<?php echo HTTP_SITEIMG_PATH?>/icon-microphone.png"  alt="" class="img-responsive margin_img_left_1"/>
                         <h1>14,000 <span> +</span></h1>
                          <h5>INBOUND '15 attendees</h5>
                    </div>
            </div>
    		</div>
		</div>

</div>

<!--end how it works-->

<!--Contact us-->

<!--end contact us-->





<script>


$(document).ready(function(e) {
var owl1 = $(".slider_how");
  
  owl1.owlCarousel({
   items : 1,
   navigation : true,
   autoWidth:true,
   loop:true,
   pagination:false,
   rewindSpeed : 1000,
   margin:10,
   slideSpeed : 1000,
   navigationText : ["<img src='"+baseUrl+"/public/img/review_slider_left_arrow.png' alt='' />","<img alt='' src='"+baseUrl+"/public/img/review_slider_right_arrow.png' />"],
  });
});

</script>