<style type="text/css">
</style>
<?php 
?>

	<div class="package_service_provider">
            			<h1>Add New<span class="pay_paln_h1"> Project </span></h1>
            </div>
    <div class="container">
<!--add Projects -->  
    		<div class="package_wrap">
            	<div class="col-sm-12">
                	<p>&nbsp;</p>
                    <h3 class="tell_us_h">Tell Us What You Need</h3>
                    <p class="we_connect">We will connect you with best suitable and qualified service providers.</p>
                </div>
           <!-- Tell us-->
            	<div class="col-sm-8 col-xs-12 job_post_outter_div">
                		 <?php echo $this->form;?>
                </div>
            <!--steps-->    
               	<div class="col-sm-4 ">
                    <div class="col-sm-12">
                        <h3 class="how_work_h3">How it works</h3>  
                        <div class="padding_10_15">
                            <div class="col-sm-3">
                                <img class="img-responsive how_it_work_inner_img" alt="" src="<?php echo HTTP_SITEIMG_PATH?>/form.png">
                            </div>
                            <div class="col-sm-9">
                                <h5 class="steps_text_heading">Step 1:</h5>
                                <span class="step_desc">Fill in the form so we get a better idea of what you need help with.</span>
                                <p>&nbsp;</p>
                            </div>
                            <hr class="clear overflow">
                            <div class="col-sm-3">
                                <img class="img-responsive how_it_work_inner_img"  alt="" src="<?php echo HTTP_SITEIMG_PATH?>/users.png">
                            </div>
                            <div class="col-sm-9">
                                <h5 class="steps_text_heading">Step 2:</h5>
                                <span class="step_desc">We will notify our database of service providers</span><br>
                                <span class="step_desc">We will connect you with suitable service providers to follow up and quote on your job.</span>
                                
                                <p>&nbsp;</p>
                            </div>
                            <hr class="clear overflow">
                            <div class="col-sm-3">
                                <img class="img-responsive how_it_work_inner_img"  src="<?php echo HTTP_SITEIMG_PATH?>/handshake.png">
                            </div>
                            <div class="col-sm-9">
                                <h5 class="steps_text_heading">Step 3:</h5>
                                <span class="step_desc">You choose the best service provider.</span>
                                <p>&nbsp;</p>
                            </div>
                            <hr class="clear overflow">
                        </div>
                    </div>        
                </div>
            </div>
    </div> 



    
      

<script type="text/javascript">



</script>



