 <?php   foreach($ReviewData as $Reviews){?>
                                                <div class="ReviewBody">  
                                                      <ul class="Review_ul">
                                                           <li class="ReviewIN">
                                                              <img class="img-thumbnail ReviewClientImg" src="<?php echo getUserImage($Reviews['user_image'],'60') ;?>" alt="" />
                                                              <div class="ReviewContent">
                                                                 <!--<span class="arrow"></span>-->
                                                                 <div class="overflow">
                                                                     <p class="ReviewRatingP inline_block"> <? echo rating_display($Reviews['review_ratings']);?></p>
                                                                     <p class="ReviewRatingP inline_block pull-right">
                                                                        <span class="ReviewClinetName"><?php echo $Reviews['user_name']; ?> &nbsp;on</span> 
                                                                        <span class="ReviewDate"><?php echo date('M d, Y',strtotime($Reviews['review_date'])); ?></span>
                                                                      </p> 
                                                                  </div>      

                                                                   <span class="ReviewMszTitleP"><p class="ReviewMszTitleP"> <?php echo $Reviews['review_title']; ?></p></span>
                                                                  <span class="ReviewMszP"><p class="ReviewMszP"> <?php echo $Reviews['review_msz']; ?></p></span>
                                                                  
                                                                 <p class="ApplentReply"></p>
                                                                  	
                                                                  <? if($Reviews['review_reply_msz']!=''){?>
                                                                	  <span class="ReviewMszReplyP"><p class="ApplentReply"> <?php echo $Reviews['review_reply_msz']; ?></p></span>
                                                                 <? }else{ ?>
                                                                 	  <p><a id="replytypebtn<?=$Reviews["review_id"]?>" class="replyBttnA pull-right" onclick="showReviewForm(<?=$Reviews["review_id"]?>)">Reply</a></p>
                                                                 <? } ?>
                                                              </div>
                            <div class="commonReplyreview formReviewReply_<?=$Reviews["review_id"]?>">
                                <form name="reply_review_form" id="reply_review_form_<?=$Reviews["review_id"]?>" >
                                	<input type="hidden" value="<?=$Reviews["review_id"]?>" id="review_id_<?=$Reviews['review_id']?>" name="review_id" />
                                    <div class="form-group">
                                    <textarea name="review_reply_msz" id="review_reply_msz" rows="2" class="form-control"></textarea>
                                    </div>
                                   <p class="text-right"> <button type="button" name="formSubmit" class="add_project" onclick="replyreviewform('<?=$Reviews["review_id"]?>')">Reply</button><button type="button" name="formSubmit" class="reviewreplycancelbtn" onclick="cancelreply('<?=$Reviews["review_id"]?>')">Cancel</button></p>
                                  <p class="text-right"> </p>

                                </form>
                            </div>

                                                           </li>  
                                                      </ul> 
                                               </div>      
 <?php } exit;?>
