 <!-- THEJAMPSTOP -->
 <!--Erorr Phtml  -->
 <!-- pages       -->
 <div class="col-md-8 col-md-offset-2" style="clear:both;">
 <br/> <br/> <br/>
 <img src="<?php echo HTTP_SITE_IMAGES?>/404.jpg"  class="center-block" style="margin-top:  0px; width:100%; border:1px solid#cccccc; padding:9px; margin-bottom:75px; clear:both;" />
 </div><br>

 <h1 style="clear:both;"><?php echo $this->message ?></h1>
<?php echo @$this->hiddenmessage ?>
  <?php if (isset($this->exception)): ?>
  
  <h3>Exception information:</h3>
  <p>
      <b>Message:</b> <?php echo $this->exception->getMessage() ?>
  </p>

<?php if(isset($this->lastQuery)){ ?>
 <p>
      <b>Last Query:</b> <pre><?php print_r($this->lastQuery); ?></pre>
  </p>
<?php } ?>


  <h3>Stack trace:</h3>
  <pre><?php echo $this->exception->getTraceAsString(); ?>
  </pre>

  <h3>Request Parameters:</h3>
  <pre><?php echo $this->escape(var_export($this->request->getParams(), true)) ?>
  </pre>

  <?php endif ?>