<?php
//braintree
  require_once ROOT_PATH.'/public/Braintree/lib/Braintree.php';
  Braintree_Configuration::environment(BRAINTREE_MODE);
  Braintree_Configuration::merchantId(BRAINTREE_MERCHANT_ID);
  Braintree_Configuration::publicKey(BRAINTREE_PUBLIC_KEY);
  Braintree_Configuration::privateKey(BRAINTREE_PRIVATE_KEY);
   
  $btClientToken = Braintree_ClientToken::generate();

?>

<style type="text/css">
</style>
<?php 
$page_desc=$this->page_desc;
$package= array();
$package= $this->package_details;
//prd($package);
$n=count($package);
$history= array();
$history =$this->package_history;
$job_id =$this->job_id;

//prd($job_id);
?>
	<div class="package_service_provider">
            			<h1>Pick a <span class="pay_paln_h1">Plan</span></h1>
            </div>
            
    <div class="containerfluid package_bg_div">
    		
<!--Package  type -->  
    		<div class="package_wrap">
            	<div class="col-sm-12">
            		<p>&nbsp;</p>
            		<p class="upper_case"><?=$page_desc['package_page_desc']?></p>
                   
                     <div class="alignments">
                        	<a class="btn view_cerdit_history  btn-lg" href ="<?php  echo $this->url(array(),"package_purchased_history")?>">Credit History</a>
                            <a class="btn view_cerdit_history  btn-lg" href ="<?php  echo $this->url(array(),"front_user_accountpage")?>">My Account</a>
                     </div>
                      <p>&nbsp;</p>
                 </div> 
                 
                 <div class="credit"> 
                 	<?php 
							$k=0;
							for($i=0;$i<$n;$i++){
								if($k>3){ $k=0;}
					?> 
                    		<div class="col-sm-3 col-xs-6 margin_padding width_xs overflow">
                            
                    			<div class="pay_div">
     <!--       Best offer ribbon -->                          		
                                   <?php /*?> <?php if($i==0){ ?>
                                    <div class="ribbon1">
                                    		<span>Best Offer</span>
                                    </div>
   <!--       purchased ribbon -->              
                                    <?php } ?><?php */?>
                                    <?php
									foreach($history as  $key => $in_history){
									 	if($package[$i]['cp_id']==$in_history['package_id']){ 
									  ?>
                                  <!--  <div class="ribbon_purchased">
                                    		<span>Purchased</span>
                                    </div>-->
                                  <? } }?>
                            		<!--<h3 class="backpack package_title_col_<=$k?>"><?php //echo $package[$i]['cp_title'] ?></h3>-->
                                   <!-- <span class="package_bottom_triangle"> </span>-->
                                   <h4 class=" MarginZero package_up_col package_uptitle_col_<?=$k?>"><?php echo $package[$i]['cp_title'] ?></h4>
                                   <h3 class="backpack package_heading_wrap_with_arrow package_title_col_<?=$k?>"><sup class="rm_sup">$</sup><?php echo $package[$i]['cp_price'] ?></h3>
                                   
                                    
                                   <?php /*?> <p class="sup_140"><sup class="rm_sup">$</sup><?php echo $package[$i]['cp_price'] ?></p><?php */?>
                                    
                                    <div class="overflow middle_contant_package_price_table">
                                    <p ><?php /*?> <img src="<?php echo HTTP_SITEIMG_PATH?>/threestars.png" alt=""><?php */?> <?=$package[$i]['cp_desc']?></p>
                                    <hr />
                                     <p ><?=$package[$i]['cp_sub_desc']?></p>
                                     <hr />
                                     <p class=" get_points">Get Credit : <span class=""><?php echo $package[$i]['cp_points'] ?></span></p>
                                      <hr />
                                      </div>
                                      
                                     <!-- <div class="package_arrow_inside"></div>-->
                                    <div class=" package_arrow_inside_<?=$k?>  package_title_col_<?=$k?>">
                                     <button onclick="payPackage(<?php echo $package[$i]['cp_id'] ?>)" type="button" class=" buy_btn btn btn-info btn-lg" data-toggle="modal" data-target="#<?php echo $package[$i]['cp_id'] ?>">Buy Package</button>
                                     </div>
                            </div>
                            
                            <div>

                            </div>    
                            
                    </div>
                    
                    <?php $k++; } ?>
                    
                </div>
                    
            </div>
			
    </div> 

<!--model for pay cnfrm-->    

<div id="payModal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header model_surepay_header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
        
        <h4 class="modal-title model_title_pay">Payment Plan</h4>
      </div>
        <div class="modal-body model_body_pay ">
        <?php $Price= $this->package_price;
		?>
            <div class="credit_msg">
                <h4>You Have To Pay $ <span id="cpprice"></span>. Are You Sure You Want To Pay?</h4>
                
          <form id="checkout" class="profile_form" method="POST" action="<?php echo $this->url(array('job_id'=>$job_id),"pay_amount")?>" method="post"> 
               			 <div id="pay_form" class="pay_form">
                	<div class="col-sm-12">
						 <?php echo $this->form->card_number; ?>
                         <?php echo $this->form->cvv; ?>
                         <?php echo $this->form->card_holder_name; ?>
                         
                     </div>
                     
                     <input id="price_input_field" type="hidden" name="package_id" value=""  />
                     
                     <div class="col-sm-12 overflow date_span_width">
                         <div class="col-sm-3">
                            <label class="dayy">Expiry date</label>
                         </div>
                         <div class="col-sm-3">
                         		<?php echo $this->form->user_credit_card_expire_month; ?>
                         </div>
                          <div class="col-sm-3">
                         		<?php echo $this->form->user_credit_card_expire_year; ?>
                         </div>
                         
                     </div>
                     <div class="col-sm-12">
                     		<?php echo $this->form->bttnsubmit; ?>
                     </div>
                </div>
                </form>
                <div class="text-center">
               		<button class="btn pay_continue btn-lg" onclick="">Continue</button>
                </div>    
            </div>
        </div>
    </div>
  </div>
</div>
    
      



<script src="https://js.braintreegateway.com/v2/braintree.js"></script>
<script>
  braintree.setup(
    "<?php echo $btClientToken; ?>", 
    "custom", {
      id: "checkout"
    });
</script>


<script type="text/javascript">


function payPackage(cp_id)
{		//alert(cp_id)
	$.ajax({
		url: baseUrl+'/package/paymodel',
		type:"GET",
		data: {current_package_id:cp_id},
	
		success: function(data) {
			$('#payModal').modal('show');
			$('#cpprice').html(data);
			$('#price_input_field').val(cp_id);
			  $(".pay_form").hide();
		 $(".pay_continue").show();
		},
	});
}

$(document).ready(function(){
    $(".pay_continue").click(function(){
        $(".pay_form").show();
		 $(".pay_continue").hide();
    });
});


</script>



