<div class="custom-form-wrapper">
			<h3 class="profile_page_headings">Services Provided by you</h3>
            
             <form name="update_form"  action="<?php echo APPLICATION_URL?>/serviceprovider/updateservice" method="get" id="update_form"  class="profile_form">
        							<?php echo $this->form->type?>
          						  <div class="form-actions text-right">
                                        <button name="bttnsubmit" id="bttnsubmit" type="submit" value="Save" class="btn blue btn-primary site_button  btn btn-default">
                                        Next</button>
									</div>
       					 </form>
 </div>

<script type="text/javascript">
	$(document).ready(function() {
	  $('[data-toggle=offcanvas]').click(function() {
		$('.row-offcanvas').toggleClass('active');
	  });
	});
	
	
</script>


 