 <!-- THEJAMPSTOP -->
 <!--Erorr Phtml  -->
 <!-- pages       -->
 <div class="container">
 <div class="row">
 <div class="col-md-8 col-md-offset-2" style="overflow:hidden">
 <br/> <br/> <br/>
 <img src="<?php echo HTTP_SITE_IMAGES?>/404.jpg"  class="center-block" style="margin-top:  0px; width:100%; border:1px solid#cccccc; padding:9px; margin-bottom:75px;" />
 </div>

</div>
</div>

 <?php /*?><div class="container">
 <div class="row">
<div class="col-md-8 col-md-offset-2 text-center" style="margin-top:50px; margin-bottom:30px;">
    <h1><?php // echo $this->message ?></h1>
    <?php echo @$this->hiddenmessage ?>
    <?php if (isset($this->exception)): ?>
    
    <h3>Exception information:</h3>
    <p>
    <b>Message:</b> <?php echo $this->exception->getMessage() ?>
    </p>
    
    <?php if(isset($this->lastQuery)){ ?>
    <p>
    <b>Last Query:</b> <pre><?php print_r($this->lastQuery); ?></pre>
    </p>
    <?php } ?>
    
    
    <h3>Stack trace:</h3>
    <pre><?php echo $this->exception->getTraceAsString(); ?>
    </pre>
    
    <h3>Request Parameters:</h3>
    <pre><?php echo $this->escape(var_export($this->request->getParams(), true)) ?>
    </pre>
    
    <?php endif ?>
</div> 
</div>
</div><?php */?>

<div class="clearfix">&nbsp;</div>