<div class="row">
 	<div class="col-md-12 ">
		<!-- BEGIN SAMPLE FORM PORTLET-->
		<div class="portlet box purple">
			<div class="portlet-title">
				<div class="caption"><i class="<?php echo $this->pageIcon?>"></i> <?php echo $this->pageHeading?> </div>
			</div>
			<div class="portlet-body">
				<?php echo $this->form;?>
			</div>
		</div>
		<!-- END SAMPLE FORM PORTLET-->
	</div>
</div>


<!-- END EXAMPLE TABLE PORTLET-->
<script type="text/javascript" charset="utf-8">
</script>

 