<div class="row">
 	<div class="col-md-12 ">
		<!-- BEGIN SAMPLE FORM PORTLET-->
		<div class="portlet box purple">
			<div class="portlet-title">
				<div class="caption"><i class="<?php echo $this->pageIcon?>"></i> <?php echo $this->pageHeading?> </div>
			</div>
			
			<div class="portlet-body">
			
				<form action="" method="post" onsubmit="return" >
 			
 					<table class="table table-striped table-bordered table-hover dataTable" id="sample_1">
						<thead>
							<tr>
								<th width="5%">S.NO</th>
                                <th>Sub Category Name</th>
                                 <th  width="10%">View</th>
                               <!-- <th  width="10%">Edit</th>-->
							</tr>
						</thead>
						<tbody>
						</tbody>
					</table>
			</form>
			
			</div>
		</div>
		<!-- END SAMPLE FORM PORTLET-->
	</div>


</div>



<!-- END EXAMPLE TABLE PORTLET-->
<script type="text/javascript" charset="utf-8">
$(document)	 .ready(function(e) {
	$('#sample_1').dataTable( {
		"bProcessing": true,
		"bServerSide": true,
 		"sAjaxSource": "<?php echo $this->baseUrl()?>/privatepanel/service/getcategoryform" ,
		"aaSorting": [],
		"aoColumnDefs": 
		 [
			{ "bSortable": false, "aTargets": [0,1,2] },
 		 	/*{ "sClass": "hidden-767", "aTargets": [ 1 ] },
			{ "sClass": "hidden-480", "aTargets": [ 5 ] },
			{ "sClass": "hidden-320", "aTargets": [6] }*/
		 ],
		"iDisplayLength":50,
	    "aLengthMenu": [[50, 100, 500, -1], [50, 100, 500, "All"]],
		"fnDrawCallback": function( oSettings ) {
			re_init();
		}
	} );
});
</script>
