<? 
$this->modelStatic = new Application_Model_Static();
$service_id = $this->category_id; 
$formfetails = $this->category_form;
$IsJobPosted = $this->IsJobPosted;
//prd($this->array_job_ids_unique);

?>
<style type="text/css">
.form-group>:first-child {display:block !important;  padding: 10px 0px; font-weight: normal; font-size: 25px;color: #525252;}
.form-group>input[type=text] {width:80%;}
.form-group>input[type=select] {width:80%;}
.checkbox { padding-left: 20px;}
.form_outter_div{border: 1px solid; padding: 10px 15px;  margin-bottom: 10px;}
</style>

<?
?>

<div class="table-toolbar">
    <div class="btn-group">
    <a href="<?php echo $this->url(array('service_id'=>$service_id),'admin_cat_add_form')?>"><button type="button" class="btn green"> <i class="fa fa-plus"></i> Add New </button></a>
    </div>	
</div>

    
    	<? $i=1;
			foreach($formfetails as $form_element) {
			
				if($form_element['c_required_optional']==1){
					$required = "required";
					}else{
						$required = "";
						}
						
						if($form_element['c_form_field_type']==0){
										$field_type ="text";
										}
										elseif($form_element['c_form_field_type']==1){
											$field_type ="textarea";
										}elseif($form_element['c_form_field_type']==2){
											$field_type ="radio";
											}elseif($form_element['c_form_field_type']==3){
												$field_type ="checkbox";
												}elseif($form_element['c_form_field_type']==4){
													$field_type ="file";
												}
						
		?>

    <div id="field_no_<?=$form_element['c_form_id']?>" class="form_outter_div">
    
 <? //prn($form_element['c_form_id']);
			
		//echo $form_element['c_form_id'];		
					/*if(isset($this->array_job_ids_unique) && !empty($this->array_job_ids_unique) && count($this->array_job_ids_unique)>0 && !in_array($form_element['c_form_id'],$this->array_job_ids_unique))*/
					//prn($this->array_job_ids_unique);
					if(!in_array($form_element['c_form_id'],$this->array_job_ids_unique))
					//if($this->array_job_ids_unique=='')
					{
					?>
                      <a href="<?php echo $this->url(array('service_id'=>$service_id,'c_form_id'=>$form_element['c_form_id']),'admin_cat_add_form')?>"><button id="sample_editable_1_new" class="btn purple"> <i class="fa fa-pencil"></i> Edit</button></a>
                
				<a onclick="suredel(<?=$form_element['c_form_id']?>)"><button id="sample_editable_1_new" class="btn red"> <i class="fa fa-trash-o"></i> Delete</button></a>
                    <?
					}
?>
        		
	
    
        <div class="form-group">
          	 <label for="<?=$field_type?>" class="required" aria-required="true"><?=$form_element['c_form_field_name']?></label>
            <?
			 if($form_element['total_options']!=0){
					$t_options= $form_element['total_options'];
					for($k=1;$k<=$t_options; $k++){
						$get_options=$this->modelStatic->Super_Get("category_form_options","category_fom_id='".$form_element['c_form_id']."'","fetchAll");
						$j=0; 
					}
						foreach($get_options as $option) {
						?>
								
                       <label class="<?=$field_type?>" for="<?=$form_element['c_form_field_name']?>-<?=$j?>">
                           <input type="<?=$field_type?>" name="<?=$form_element['c_form_field_name']?>" id="<?=$form_element['c_form_field_name']?>-<?=$j?>" value="" title="Please select one options" class="<?=$required?>" required="" aria-required="true" aria-invalid="false"><?=$option['option_text'];?>
                       </label>
		    <?    $j++; }  ?>
              <? if($form_element['c_other']==1){ ?>
              			<label class="<?=$field_type?>" for="<?=$form_element['c_form_field_name']?>-<?=$j?>">
                         <input type="<?=$field_type?>" name="<?=$form_element['c_form_field_name']?>" id="<?=$form_element['c_form_field_name']?>-<?=$j?>" value="" title="Please select one options" class="<?=$required?>" required="" aria-required="true" aria-invalid="false">	<input type="text" placeholder="Other" />
                        </label>
			 <?  }  ?>
				   
                   
				   <?
					} else {	
			?>
            <input type="<?=$field_type?>" name="<?=$form_element['c_form_field_name']?>" id="<?=$form_element['c_form_field_name']?>" value="" class="form-control <?=$required?>" required="" aria-required="true" aria-invalid="false">
            <? } ?>
        </div>
        
   
   </div>     
	<?  $i++; } ?>
    
    <div class="form_outter_div">
    	 <?php echo $this->form->job_deadline;?>
    </div>
    
    <div class="form_outter_div">
    	 <?php echo $this->form->job_anything_else_know;?>
    </div>
    
    <div class="form_outter_div">
    	 <?php echo $this->form->job_phone_client;?>
    </div>
    
    <div class="form_outter_div">
    	 <?php echo $this->form->client_zip_code;?>
    </div>
    
    <div class="form_outter_div">
    	 <?php echo $this->form->how_receive_quote;?>
    </div>
    
<script type="text/javascript">



function suredel(id){
	var del = confirm("Are you sure you want to delete this question?");
	if(del==true)
	{	
		$.ajax({
		url:baseUrl+'/privatepanel/service/deleteformcat',
		data : {c_form_id:id},
		success:function(data){
				window.location=window.location.href;
			}
		});
	}
}
</script>