<style>
.checkbox-container {
    position: absolute;
    display: inline-block;
    margin-left: 9px;
	margin-top: 4px;
    width: 15px;
    height: 15px;
    overflow: hidden;
	border:1px solid #bcbcbc;
}
.chk
{
	height: 17px;
    width: 17px;
	background: none repeat scroll 0 0 rgba(0, 0, 0, 0);
    border: medium none;
    display: inline-block;
	/*-webkit-appearance: none;*/
    -moz-appearance: none;
    appearance: none;
	margin-left: 3px;
    padding: 0;
	border: none;
    position: relative;
	top:-2px;
	left:-2px
}
input[type="checkbox"]:focus
{
	border:none;
	outline:none;
}
div.checker
{
	margin-left:0px;
}
div.checker span
{
	margin-left: -3px !important;
    margin-top: -3px !important;
}
/* saf3+, chrome1+ */
@media screen and (-webkit-min-device-pixel-ratio:0) {
.chk
{
	top:1px;
}
}
</style>

<div class="row">
	<div class="col-md-12">
		<!-- BEGIN SAMPLE FORM PORTLET-->
		<div class="portlet box purple">
			<div class="portlet-title">
				<div class="caption">
					<i class="<?php echo $this->pageIcon?>"></i><?php echo $this->pageHeading?>  
				</div>
				
			</div>
			<div class="portlet-body form">             
				<div class="form-body">
					<form method="post" enctype="multipart/form-data">
                        <div>
                        	<div class=" form-group " id="q_course_id_div">
                           	<?=$this->form->topic_name?>
                            </div>
                        	
                            <div style="height:10px; clear:both">&nbsp;</div>
                            
                            <?=$this->form->bttnsubmit;?>
                            
                        </div>
                    </form>
				</div>
			</div>
		</div>
		<!-- END SAMPLE FORM PORTLET-->
	</div>
</div>