<?php if(($this->current_controller=="index" || ($this->current_controller=="static" and $this->current_action=='faq' ))){?>
<!-- Carousel
    ================================================== -->

<div id="myCarousel" class="carousel slide"> 
  <!-- Indicators --> 
  <!--<ol class="carousel-indicators">
	  	<?php 
			$active = "active";
			foreach($this->slider_images as $values){?>
 			 <li data-target="#myCarousel" data-slide-to="<?php echo $values['slider_image_id']?>" class="<?php echo $active;$active="";?>"></li>
 		<?php  }?>
      </ol>-->
  
  <div class="carousel-inner">
    <?php 
			$active = "active";
			foreach($this->slider_images as $values){ ?>

    
    
    <div class="item <?php echo $active;$active="";?> text-center" >
              	<img style="display:inline-block;" src="<?php echo HTTP_SLIDER_IMAGES_PATH."/".$values['slider_image_path']?>" alt="<?php echo $values['slider_image_alt']?>"> 
               <? //prd(HTTP_SLIDER_IMAGES_PATH."/".$values['slider_image_path']); ?>
				<div class="carousel-caption">
				<? if($this->current_controller=="index" and $this->current_action=="index"){?>
                		
                    <p class="main_title"><?=$values['slider_image_title']?></p>
                    <p class="sub_title"> <?=$values['slider_image_alt']?></p> 
                    <p class="margin30class" > <a  class="how_it_works" href="<?php echo $this->url(array(),'how_it_work')?>" >How it Works</a></p> 
                
 				 <? }?>
                 <? if($this->current_controller=="static" and $this->current_action=="faq"){?>
                		
                    <p class="main_title"><?=$values['slider_image_title']?></p>
                   
                
 				 <? }?>
             		
				</div>
 			</div>
    
    <?php  }?>
    
   
  </div>
  <? if(($this->current_controller=="index")){?>
   <div  class="search_div">
   			<form name="search_form" id="search_form" method="post" action="<?=$this->baseUrl()?>">
      <div class="form_bg">
        <div class="inline-block textboxdiv" >
          <input type="text" name="cave"  class="form-control-new" placeholder="What are you craving?"  id="cave"  value=""  />
        </div>
        <div class="inline-block textboxdiv">
        	<input type="text" name="food" class="form-control-new"  placeholder="Where will you eat?"   id="food"  value=""  />
        	
         </div>
        <div class="inline-block buttondiv"> 
                  <input type="submit"   name="search" id="search" class="search_btn"  value="Search"  />

        </div>
        
      </div>
    </form>
   </div>
   <? }?>
    <!--<a class="left carousel-control" href="#myCarousel" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
      <a class="right carousel-control" href="#myCarousel" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a> -->
</div>
<!-- /.carousel --> 

<script type="application/x-javascript">
	
$(document).ready(function(e) {
	$('.carousel').carousel({
	  interval: 5000
	})
});

</script>
<?php  } ?>
