<?php if($this->current_controller=="index" and $this->current_action=="index" ){?>
 <!-- Carousel
    ================================================== -->
   <div class="row relativeDiv">
   	<img src="<?php echo HTTP_SITE_IMAGES ?>/slidermain.jpg" class="img-responsive" width="100%"   />
    <div class="discoverdiv  hidden-xs">
    	<div class="discover_inner">
        	<div><span>DISCOVER</span> the best place to </div>
            <div><span>GRAB A DRINK</span> in your city..</div>
        	<div class="explore_div">
            	<div class="expore_inner">Explore Now</div>
            </div>
        </div>
    </div>
    
   </div>
</script>


<?php  } ?>