<?php if(isset($this->layout_show_map) and $this->layout_show_map){?>
<p>&nbsp;</p>
<div class="map-container">
	<div id="contact-map-canvas" style="width:100%; min-height:340px;"></div>
</div>1111111
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDZmQj_e_DJQVFr2hiJr01pvFYZUQt83mI&libraries=places,geometry&amp;sensor=false"  type="text/javascript"></script>
<script type="text/javascript">
var map;
	function initialize() {
		var mapOptions = {
			zoom: 16,
			center: new google.maps.LatLng(<?php echo $this->site_configs['latitude']?>,<?php echo $this->site_configs['longitude']?>),
			mapTypeId: google.maps.MapTypeId.ROADMAP,
			scrollwheel: false,
			zoomControlOptions: {
     			style: google.maps.ZoomControlStyle.SMALL,
     		},
			 mapTypeControlOptions: {
			  style: google.maps.MapTypeControlStyle.DROPDOWN_MENU
			},
			
 		};
		
		map = new google.maps.Map(document.getElementById('contact-map-canvas'),mapOptions);
		marker = new google.maps.Marker({map: map});
 		marker.setPosition(mapOptions.center);
		
	}
google.maps.event.addDomListener(window, 'load', initialize);
</script>
<?php  } ?>